# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
#
jobs:
  testit:
    docker:

      # specify the node version in this tag
      - image: circleci/node:10.14.2 # Latest LTS

      # start a ganache testing suite
      - image: trufflesuite/ganache-cli
        command: [ -p, "8080",          # PORT
                   -i, "4321",          # NETWORK ID
                   -a, "15",            # NUMBER OF ACCTS
                   -e, "1000000000000", # START BAL
                   -l, "7600000",       # GAS LIMIT
                   -g, "20000000000",   # GAS COST
                 ]

    working_directory: ~/repo

    steps:

      # Install global node modules as sudo
      - run: sudo npm i -g truffle

        # Grab the repo
      - checkout

      # Get/cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install/update dependencies as needed
      - run: npm i

      # Set/save cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests via "test" script in package.json
      - run: npm test

workflows:
  version: 2
  branch-testing:
    jobs:
      - testit:
          filters:
            branches:
              only: /(^test\-.*)|(master)/