## Circle CI config for testing with:
## - CI workflows
## - Multiple languages
## - Branch filtering for jobs

jobs:

#----------------------------------------#
#-- UNIT TESTING FOR SOLIDITY BRANCHES --#
#----------------------------------------#
  unit_test_truffle:
    docker:
      # Primary docker image containing nodejs
      - image: circleci/node:10.14.2 # Latest LTS

      # Start a ganache test suite inside the primary image
      - image: trufflesuite/ganache-cli
        # This config must match the solidity project's truffle.js module config
        command: [ -p, "8080",          # PORT
                   -i, "4321",          # NETWORK ID
                   -a, "15",            # NUMBER OF ACCTS
                   -e, "1000000000000", # START BAL
                   -l, "7600000",       # GAS LIMIT
                   -g, "20000000000",   # GAS COST
                 ]

    working_directory: ~/repo

    environment:
      CI_LANGUAGE_PREFIX: sol

    steps:
      # Get repository from VCS
      - checkout

      # Run test suite script
      - run:
          name: Execute Service Runner
          command: |
            ./runner.sh

      # Store testing artifacts
      - store_artifacts:
          path: ~/repo/services/artifacts

#--------------------------------------#
#-- UNIT TESTING FOR NODEJS BRANCHES --#
#--------------------------------------#
  unit_test_js:
    docker:
      # Primary docker image containing nodejs
      - image: circleci/node:10.14.2 # Latest LTS

    working_directory: ~/repo

    environment:
      CI_LANGUAGE_PREFIX: js

    steps:
      # Get repository from VCS
      - checkout

      # Run test suite script
      - run:
          name: Execute Service Runner
          command: |
            ./runner.sh

      # Store testing artifacts
      - store_artifacts:
          path: ~/repo/services/artifacts

#--------------------------------------#
#-- UNIT TESTING FOR GOLANG BRANCHES --#
#--------------------------------------#
  unit_test_go:
    docker:
      # Primary docker image containing golang
      - image: circleci/golang:1.11

    working_directory: ~/repo

    environment:
      CI_LANGUAGE_PREFIX: go

    steps:
      # Get repository from VCS
      - checkout

      # Run test suite script
      - run:
          name: Execute Service Runner
          command: |
            ./runner.sh

      # Store testing artifacts
      - store_artifacts:
          path: ~/repo/services/artifacts

#----------------------------------------#
#-- UNIT TESTING FOR DARTLANG BRANCHES --#
#----------------------------------------#
  unit_test_dart:
    docker:
      # Primary docker image containing nodejs and bundled browsers
      - image: swissarmybud/dart:2.1-browsers

    working_directory: ~/repo

    environment:
      CI_LANGUAGE_PREFIX: dart

    steps:
      # Get repository from VCS
      - checkout

      # Run test suite script
      - run:
          name: Execute Service Runner
          command: |
            ./runner.sh

      # Store testing artifacts
      - store_artifacts:
          path: ~/repo/services/artifacts

workflows:
  version: 2
  testing-suite:
    jobs:
      - unit_test_go:
          filters:
            branches:
              only: /(^go\-.*)/
      - unit_test_truffle:
          filters:
            branches:
              only: /(^sol\-.*)/
      - unit_test_js:
          filters:
            branches:
              only: /(^js\-.*)/
      - unit_test_dart:
          filters:
            branches:
              only: /(^dart\-.*)/
